//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exercise4.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EMP_ID { get; set; }
        public string EMP_NAME { get; set; }
        public int EMP_AGE { get; set; }
        public System.DateTime EMP_DOB { get; set; }
        public Nullable<System.DateTime> EMP_DOJ { get; set; }
    }
}
