//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exercise4.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MyEntities : DbContext
    {
        public MyEntities()
            : base("name=MyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee> Employees { get; set; }
    
        public virtual ObjectResult<GET_EMPLOYEEDETAILS_Result> GET_EMPLOYEEDETAILS(Nullable<int> eMP_ID)
        {
            var eMP_IDParameter = eMP_ID.HasValue ?
                new ObjectParameter("EMP_ID", eMP_ID) :
                new ObjectParameter("EMP_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_EMPLOYEEDETAILS_Result>("GET_EMPLOYEEDETAILS", eMP_IDParameter);
        }
    }
}
