-- Query for Create Table
CREATE TABLE [dbo].[Employees](
	[EMP_ID] [INT] IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[EMP_NAME] [NVARCHAR](100)  NOT NULL,
	[EMP_AGE] [INT]  NOT NULL,
	[EMP_DOB] [DATETIME] NOT NULL,
	[EMP_DOJ] [DATETIME] DEFAULT CURRENT_TIMESTAMP
)
GO

SELECT * FROM Employees

-- Sample Data
INSERT INTO Employees (EMP_NAME, EMP_AGE, EMP_DOB) VALUES('Mushtaq', '25', '1993-12-12')
INSERT INTO Employees (EMP_NAME, EMP_AGE, EMP_DOB) VALUES('Fazil', '23', '1995-07-08')

-- Sample Procedure
IF EXISTS(SELECT 1 FROM SYS.procedures WHERE NAME = 'GET_EMPLOYEEDETAILS')
BEGIN
	DROP PROCEDURE GET_EMPLOYEEDETAILS
END
GO
-- GET_EMPLOYEEDETAILS 1
CREATE PROC GET_EMPLOYEEDETAILS(@EMP_ID INTEGER)
AS
BEGIN
	SELECT * FROM Employees WHERE EMP_ID = @EMP_ID
END
GO